/*
 * This file is generated by jOOQ.
 */
package lv.bogatirjovs.currencycalculatorkotlin.jooq


import kotlin.collections.List

import lv.bogatirjovs.currencycalculatorkotlin.jooq.tables.CurrencyConversion

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Currency : SchemaImpl("currency", DefaultCatalog.DEFAULT_CATALOG) {
    companion object {

        /**
         * The reference instance of <code>currency</code>
         */
        val CURRENCY: Currency = Currency()
    }

    /**
     * The table <code>currency.currency_conversion</code>.
     */
    val CURRENCY_CONVERSION: CurrencyConversion get() = CurrencyConversion.CURRENCY_CONVERSION

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        CurrencyConversion.CURRENCY_CONVERSION
    )
}
