currency-conversion:
  defaultFee: 0.01
  ecb-api: https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml
server:
  address: 0.0.0.0
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/currency
    username: currency
    password: currency
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: POSTGRES