/*
 * This file is generated by jOOQ.
 */
package lv.bogatirjovs.currencycalculatorkotlin.jooq.tables


import java.math.BigDecimal
import java.time.LocalDateTime

import kotlin.collections.Collection

import lv.bogatirjovs.currencycalculatorkotlin.jooq.Currency
import lv.bogatirjovs.currencycalculatorkotlin.jooq.keys.CURRENCY_CONVERSION_PKEY
import lv.bogatirjovs.currencycalculatorkotlin.jooq.tables.records.CurrencyConversionRecord

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CurrencyConversion(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, CurrencyConversionRecord>?,
    parentPath: InverseForeignKey<out Record, CurrencyConversionRecord>?,
    aliased: Table<CurrencyConversionRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<CurrencyConversionRecord>(
    alias,
    Currency.CURRENCY,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>currency.currency_conversion</code>
         */
        val CURRENCY_CONVERSION: CurrencyConversion = CurrencyConversion()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CurrencyConversionRecord> = CurrencyConversionRecord::class.java

    /**
     * The column <code>currency.currency_conversion.id</code>.
     */
    val ID: TableField<CurrencyConversionRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>currency.currency_conversion.amount</code>.
     */
    val AMOUNT: TableField<CurrencyConversionRecord, BigDecimal?> = createField(DSL.name("amount"), SQLDataType.NUMERIC(19, 4).nullable(false), this, "")

    /**
     * The column <code>currency.currency_conversion.from_currency</code>.
     */
    val FROM_CURRENCY: TableField<CurrencyConversionRecord, String?> = createField(DSL.name("from_currency"), SQLDataType.VARCHAR(3).nullable(false), this, "")

    /**
     * The column <code>currency.currency_conversion.to_currency</code>.
     */
    val TO_CURRENCY: TableField<CurrencyConversionRecord, String?> = createField(DSL.name("to_currency"), SQLDataType.VARCHAR(3).nullable(false), this, "")

    /**
     * The column <code>currency.currency_conversion.fee</code>.
     */
    val FEE: TableField<CurrencyConversionRecord, BigDecimal?> = createField(DSL.name("fee"), SQLDataType.NUMERIC(5, 4).nullable(false), this, "")

    /**
     * The column <code>currency.currency_conversion.status</code>.
     */
    val STATUS: TableField<CurrencyConversionRecord, String?> = createField(DSL.name("status"), SQLDataType.VARCHAR(20).nullable(false), this, "")

    /**
     * The column <code>currency.currency_conversion.conversion_rate</code>.
     */
    val CONVERSION_RATE: TableField<CurrencyConversionRecord, BigDecimal?> = createField(DSL.name("conversion_rate"), SQLDataType.NUMERIC(19, 6), this, "")

    /**
     * The column <code>currency.currency_conversion.result</code>.
     */
    val RESULT: TableField<CurrencyConversionRecord, BigDecimal?> = createField(DSL.name("result"), SQLDataType.NUMERIC(19, 6), this, "")

    /**
     * The column <code>currency.currency_conversion.created_at</code>.
     */
    val CREATED_AT: TableField<CurrencyConversionRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<CurrencyConversionRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<CurrencyConversionRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<CurrencyConversionRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>currency.currency_conversion</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>currency.currency_conversion</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>currency.currency_conversion</code> table reference
     */
    constructor(): this(DSL.name("currency_conversion"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Currency.CURRENCY
    override fun getIdentity(): Identity<CurrencyConversionRecord, Long?> = super.getIdentity() as Identity<CurrencyConversionRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<CurrencyConversionRecord> = CURRENCY_CONVERSION_PKEY
    override fun `as`(alias: String): CurrencyConversion = CurrencyConversion(DSL.name(alias), this)
    override fun `as`(alias: Name): CurrencyConversion = CurrencyConversion(alias, this)
    override fun `as`(alias: Table<*>): CurrencyConversion = CurrencyConversion(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): CurrencyConversion = CurrencyConversion(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): CurrencyConversion = CurrencyConversion(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): CurrencyConversion = CurrencyConversion(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): CurrencyConversion = CurrencyConversion(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): CurrencyConversion = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): CurrencyConversion = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): CurrencyConversion = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): CurrencyConversion = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): CurrencyConversion = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): CurrencyConversion = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): CurrencyConversion = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): CurrencyConversion = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): CurrencyConversion = where(DSL.notExists(select))
}
