/*
 * This file is generated by jOOQ.
 */
package lv.bogatirjovs.currencycalculatorkotlin.jooq.tables.references


import lv.bogatirjovs.currencycalculatorkotlin.jooq.tables.CurrencyConversion



/**
 * The table <code>currency.currency_conversion</code>.
 */
val CURRENCY_CONVERSION: CurrencyConversion = CurrencyConversion.CURRENCY_CONVERSION
